### ISSUE TITLE
Issue with the ATC Link

### ISSUE THREAD

**Issue by 4deetz** [Dam998/shopify-monitor#1]
Hi i noticed a problem with the ATC link
When we click on it, it puts an error. I managed to correct the problem by removing the .js from the link.  I suggest you make this change on your next update

Otherwise everything works perfectly, thank you
(in the future, an AIO monitor would also be perfect lol)

**Comment by Dam998** [comment]
Hi, thanks for the feedback
Can you send me the site that gives you the error? Because the sites I have tested work well

**Comment by 4deetz** [comment]
Yep, look :

With the .js : http://prntscr.com/s9ppkm
Without the .js : http://prntscr.com/s9pqa0

**Comment by 4deetz** [comment]
![test1](https://user-images.githubusercontent.com/53958175/80868317-11d14100-8c9a-11ea-997c-fcbc8c590881.png)


Last thing, if you can add these features:

- Ability to add a logo to the embed
- To be able to add the small description below (on the screen)

**Comment by Dam998** [comment]
Wow, okay
I understand what happend

The link with .js is working but it execute only the command to the site, so you see a lot lines of code that describe the product (these lines are ok, they notify you that all works fine) but if the link is without the .js the site execute the command and automaticcallu redirect to the cart
That's usefull to know, thank you so much, I'll do a new version now

And if you like my work, please, add a star my project. This can help me (and maybe in the future this monitor would became a AIO Monitor ;) )

**Comment by Dam998** [comment]
Yes I will
In the future I will add more configuration settings in config.json to also customize the discord message
