### ISSUE TITLE
npm start not working 

### ISSUE THREAD

**Issue by georgez997** [Dam998/shopify-monitor#19]
thats a screenshot after starting it
https://gyazo.com/5e0f98db787c9c04aad1d66de4b93ab3

this is the config
https://gyazo.com/498dbada7a7e39acdffb3cb1a4e374b2

**Comment by Brandon1419** [comment]
I'm having the same problem

**Comment by Brandon1419** [comment]
Any help with this @Dam998 ?

**Comment by Dam998** [comment]
@georgez997 check how you wrote your webhook url pls

**Comment by Dam998** [comment]
@Brandon1419 try to update your node version

**Comment by Brandon1419** [comment]
> @Brandon1419 try to update your node version

Thank you!!! Worked. Used these commands below:

sudo npm cache clean -f
sudo npm install -g n
sudo n stable
sudo n latest
