### ISSUE TITLE
Maybe I made a mistake

### ISSUE THREAD

**Issue by 4deetz** [Dam998/shopify-monitor#3]
Hey Dam, 
I launched the monitor at 5.30pm and it still hasn't detected any items. I'm afraid I made a mistake. Can you check? Thanks

   },
    "requestTiming": 30000,
    "__KEYWORDS_EXPLAINED" : "In this default example that I've created the monitor will notify you if find a Nike product in hanon or sensinko site, and it'll notify if find a New Balance or Adidas Yeezy product only in hanon site",
    "keywords": [["Nike"]],
    "sites": [
        {
            "url": "hanon-shop.com",
            "keywords": [["Adidas"],["New Balance"],["Yeezy"],["Nike","Jordan"]]
        },
        { "url": "sesinko.com" },
        { "url": "thenextdoor.fr" },
		{ "url": "a-ma-maniere.com" },
		{ "url": "noirfonce.fr" },
		{ "url": "pampamlondon.com" },
		{ "url": "de.afew-store.com" },
		{ "url": "extrabutterny.com" }
    ]
}

**Comment by Dam998** [comment]
Hi,
What's your time zone? 
However, maybe no one nike product (or adidas, new balance, yeezy or nike jordan for the hanon site) changed in any sites

But if you let me know your time zone I'm going to investigate if there is a problem

**Comment by Dam998** [comment]
If you want more opportunities to catch a product changes and see the monitor work, remove all keywords

**Comment by 4deetz** [comment]
My time zone : (UTC+2)

Maybe i'll do that (remove all the keywords)

**Comment by 4deetz** [comment]
},
"requestTiming": 30000,
"__KEYWORDS_EXPLAINED" : "In this default example that I've created the monitor will notify you if find a Nike product in hanon or sensinko site, and it'll notify if find a New Balance or Adidas Yeezy product only in hanon site",
"keywords": [["Nike"]],
"sites": [
{
{ "url": "hanon-shop.com" },
{ "url": "sesinko.com" },
{ "url": "thenextdoor.fr" },
{ "url": "a-ma-maniere.com" },
{ "url": "noirfonce.fr" },
{ "url": "pampamlondon.com" },
{ "url": "de.afew-store.com" },
{ "url": "extrabutterny.com" }
]
}

**Comment by 4deetz** [comment]
Like this?

**Comment by Dam998** [comment]
Yes, right

**Comment by 4deetz** [comment]
Thanks Dam, I'll test

**Comment by 4deetz** [comment]
It's working, thanks a lot!
I support you enormously in your project.
Are you looking to work with someone?

**Comment by Dam998** [comment]
Thank you very much for your support

Right now no, I do it as a hobby but I have a lot of projects in my mind, if I find enough time to do them
After I finish implementing proxies on this shopify monitor, I will start another project

**Comment by 4deetz** [comment]
No worries, I hope it will be the aio monitors aha
