### ISSUE TITLE
Webhook Question

### ISSUE THREAD

**Issue by Brandon1419** [Dam998/shopify-monitor#31]
@Dam998 If I were to add multiple Webhook URLs into the webhook array in the config.json file, would it send to all those webhooks? Wanted to ask before I tried it.

**Comment by bushaaaa** [comment]
@Brandon1419 yes, in one of the lasts update he added the possibiliy to use more than one webhook in the same script.

**Comment by Brandon1419** [comment]
yep. It does work Thanks
