### ISSUE TITLE
What's the lowest delay you recommend?

### ISSUE THREAD

**Issue by Amejame** [Dam998/shopify-monitor#6]
What's the lowest delay you recommend?

**Comment by Dam998** [comment]
Hi,
To be sure and always avoid the bans, I recommend 30,000 (30 seconds), I wrote all my suggestions in the readme file, read it all to see all my recommendations.
In the next version the monitor will support proxies, so you can reduce the time based on how many you use.
For example with 4 ip (3 proxy and the ip of your PC / server) you can stay safe with 7500 (7.5 seconds) and get very high performance

If you like my work, please add a star to my repository to support me, I'm trying to understand if this type of projects interest people, I could publish others for other sites

**Comment by Amejame** [comment]
Okay then, I'm waiting for a proxy update, cause this delay is so big that I would like to make it as fast as possible

**Comment by Dam998** [comment]
Yes, but understand that 30 seconds doesn't mean that if a site restock at 18:00:00 you always get notification at 18:00:30, it's mean that the maximum is 18:00:30 but you can get notification from monitor at 18:00:01. 30 seconds is the maximum uncertainty

**Comment by Dam998** [comment]
however I tried also with 25 and it's ok, but to always safe, after all my tests, 30 seconds is the time that I recommend

**Comment by Dam998** [comment]
Version with proxy is online now, pull it and rexecute 'npm install'

**Comment by Amejame** [comment]
Great to hear that!

**Comment by Amejame** [comment]
I think it doesn't work like it should. I added 14 proxies, set delay to 2000 and I'm getting an errors like this :
![image](https://user-images.githubusercontent.com/61716010/81349281-029a2b00-90c0-11ea-9049-c4ea984eb524.png)

Have you tried it yourself?

**Comment by Dam998** [comment]
I need more information to help you, do this:
- Send me all the error message
- Execute the script without proxies, does it work without proxies?

**Comment by Amejame** [comment]
Yeah, the thing is it works with proxies also but I expected it work 15x faster with 15 proxies. It seems like proxies the monitor doesn't take the proxies now and still monitors using one IP

**Comment by Dam998** [comment]
li hai aggiunti correttamente i proxies?
Did you read the configuration settings section in the readme file?

I don't know why your proxies doesn't work, are they ipv6? did you buy them or you found them online for free?

maybe if you send me all the message error I can help you to investigate the problem, if you don't send me nothing I cannot help you

**Comment by Amejame** [comment]
],
    "proxiesList": ["https://{6VIN1P}:{MmKsTo}@{42.135.71.181}:{8000}"]
}
That's how I added proxy address. It's fake just to give an example to you. I have read the configuration settings. They are private ipv4. I bought them. 
There is the full error: 
![image](https://user-images.githubusercontent.com/61716010/81356984-d936ca80-90d2-11ea-8d81-75d965ea3a88.png)

Have you tried the monitor with proxies yourself?

**Comment by Dam998** [comment]
Yes of sure
Try to write the proxy link like http:// and not https://
I know that your proxy is https but try it because I have proxies https and work if write http://

**Comment by Amejame** [comment]
I have tried both versions. Could you please give me any of your proxies to check if the real trouble is in there? Please give me a discord to contact you

**Comment by Dam998** [comment]
this is my discord contact: ipap#2079
but I'll not send you my personal proxies to try it, if you want do this test, send to me your proxies and I'll looking for where is the problem
