### ISSUE TITLE
Not picking up items

### ISSUE THREAD

**Issue by tbowen00** [Dam998/shopify-monitor#7]
I set it up and get the notification on my discord but I've been running for 5 hours on 7 sites and not one thing picked up. Is this due to the script or nothing being loaded?

**Comment by Tainguynpdx** [comment]
> I set it up and get the notification on my discord but I've been running for 5 hours on 7 sites and not one thing picked up. Is this due to the script or nothing being loaded?

currently having the same issue

**Comment by Dam998** [comment]
did you insert keywords in config.json file?
can you send me the sites that you're monitoring? I'll check if something changed on their website in the past 5 hours

**Comment by Tainguynpdx** [comment]
> did you insert keywords in config.json file?
> can you send me the sites that you're monitoring? I'll check if something changed on their website in the past 5 hours

Used kith, and keywords are [["Adidas"],["New Balance"],["Nike","Jordan"]] 
and also done none keywords [[""],[""],[""]]

**Comment by tbowen00** [comment]
"requestTiming": 30000,
    "__KEYWORDS_EXPLAINED" : "In this default example that I've created the monitor will notify you if find a Nike product in hanon or sensinko site, and it'll notify if find a New Balance or Adidas Yeezy product only in hanon site",
    "keywords": [["Nike"]],
    "sites": [
        {
            "url": "hanon-shop.com",
            "keywords": [["Nike", "Jordan"], ["Nike"], ["Adidas", "Yeezy"], ["Yeezy"], ["Off", "White"] ,["New, Balance"]]

It's not letting me screenshot for some reason but this is how I entered everything

Sites being monitored are: Kith.com Undefeated.com, hanon-shop.com, starcowparis.com, cncpts.com, dsmny, dsml, deadstock.com

**Comment by tbowen00** [comment]
![monitor screenshot](https://user-images.githubusercontent.com/62860408/81430181-a3bacd00-9124-11ea-84ed-e13db52b22b5.png)

**Comment by Dam998** [comment]
response to **tbowen00**:
starcoparis, deadstock, dsmny, dsml, deadstock are not shopify monitor, so remove it. this is a shopify monitor, you are monitoring only kith, Undefeated and hanon-shop.com

and, as I explained in the readme file, with keywords: [["Nike"]] as you setted before, monitor will notify you only if a nike product change in these sites

in conclusion: remove the sites that are not shopify and, my advice, if you want more chance to see the monitor work remove all keywords, don't leave it empty array, remove it, like this:

![image](https://user-images.githubusercontent.com/23696659/81430917-928fb180-9160-11ea-8d17-08d025cdea93.png)

**Comment by Tainguynpdx** [comment]
By chance you could copy and paste that for us? that looks alot easier to read for me.

**Comment by Dam998** [comment]
**Tainguynpdx** did you also remove keywords [["Nike"]]? because if you set keywords in the field out from sites list these keywords work on all sites in the sites list

or maybe the problem is only that kith didn't update their products, add more sites

**Comment by Dam998** [comment]
{
    "mongodb_uri": "mongodb://127.0.0.1:27017/shopify",
    "webhook_url": [
        "DISCORD_WEBHOOK_URL"
    ],
    "discord_message_settings": {
        "botImage": "https://cdn.discordapp.com/embed/avatars/0.png",
        "botName": "Shopify monitor",
        "footerDescription": "",
        "footerImage": "",
        "timeOfNotification": true
    },
    "requestTiming": 7500,
    "__KEYWORDS_EXPLAINED" : "In this default example that I've created the monitor will notify you if find a Nike product in hanon or sensinko site, and it'll notify if find a New Balance or Adidas Yeezy product only in hanon site",
    "sites": [
        { "url": "hanon-shop.com" },
        { "url": "sesinko.com" },
        { "url": "thenextdoor.fr" },
        { "url": "a-ma-maniere.com" },
        { "url": "noirfonce.fr" },
        { "url": "pampamlondon.com" },
        { "url": "de.afew-store.com" },
        { "url": "extrabutterny.com" }
    ],
    "proxiesList": [
    ]
}

**Comment by Dam998** [comment]
try this config.json settings, I'm sure you will receive some notifications

add also this site: patta.nl

**Comment by Dam998** [comment]
please change the requestTime, I made a mistake to doesn't change it, if you don't have proxies and leave that time, after some times you'll be banned

**Comment by tbowen00** [comment]
well that would make sense lol, just went off other discord groups who had those sites under shopify, should've known. So if we want to run for multiple keywords for these sites, should we just do different configs for each keyword?

**Comment by Tainguynpdx** [comment]
Yes testing now with 30k requesttime to avoid ban.

**Comment by Dam998** [comment]
to check if a site is a shopify site you have to search for url/admin and see if it redirect you to sopify login page
example https://www.hanon-shop.com/admin

if you want set keywords only for a site, add field **keywords** in the same object where you have the url, like this {url: hanon-shop.com, keywords: [["Nike"]]}, and the monitor will notify you if it find a product nike changed in hanon-shop site

if you want set keywords to all list of your sites, add the field **keywords** out from the siteslist

I hope you understand me

**Comment by Dam998** [comment]
I want that you understand that if you add a keyword, only if a product with that keyword change, the monitor notify you, so if you want to see all the products that change, don't set keywords fields

**Comment by Tainguynpdx** [comment]
Okay with script i got it working

last question.
I have a list of shopify site in the script, by keywords do i have to put keywords under each and everyone of them? or could i just have one section of keywords that would run all site 

thank you for the help again bro.

**Comment by Tainguynpdx** [comment]
any reason why kith and undefeated doesnt pick up?

**Comment by Dam998** [comment]
because they didn't update their products, or if you setted some keywords: they didn't update products that match with that keywords

**Comment by Dam998** [comment]
I close this for inactivity, reopen it if you need it
