### ISSUE TITLE
Would like to now if setting file written correctly 

### ISSUE THREAD

**Issue by c0deless** [Dam998/shopify-monitor#8]
Hi there I just wanted to know if the config file that I have written is good .
Because it seems the monitor does not seem to filter keywords as output .

there is the config file :

  },
    "requestTiming": 30000,
    "__KEYWORDS_EXPLAINED" : "",
    "keywords": [[""]],
    "sites": [
        {
            "url": "hanon-shop.com",
            "keywords": [["Adidas","Yeezy"],["Nike","SB"],["Nike","Air","Jordan","1"],["Nike","Jordan","1"],["Nike","Jordan","11"],["Nike","Jordan","4"],["Nike","AIR","FORCE","1"],["Nike","AIR","MAX","90$
        },
        {
            "url": "a-ma-maniere.com",
           "keywords": [["Adidas","Yeezy"],["Nike","SB"],["Nike","Air","Jordan","1"],["Nike","Jordan","1"],["Nike","Jordan","11"],["Nike","Jordan","4"],["Nike","AIR","FORCE","1"],["Nike","AIR","MAX","90"$
        },
        {
            "url": "apbstore.com",
           "keywords": [["Adidas","Yeezy"],["Nike","SB"],["Nike","Air","Jordan","1"],["Nike","Jordan","1"],["Nike","Jordan","11"],["Nike","Jordan","4"],["Nike","AIR","FORCE","1"],["Nike","AIR","MAX","90"$
        },
         {
            "url": "alifenewyork.com",
           "keywords": [["Adidas","Yeezy"],["Nike","SB"],["Nike","Air","Jordan","1"],["Nike","Jordan","1"],["Nike","Jordan","11"],["Nike","Jordan","4"],["Nike","AIR","FORCE","1"],["Nike","AIR","MAX","90"$
        },
        {
            "url": "antisocialsocialclub.com",
           "keywords": [["Adidas","Yeezy"],["Nike","SB"],["Nike","Air","Jordan","1"],["Nike","Jordan","1"],["Nike","Jordan","11"],["Nike","Jordan","4"],["Nike","AIR","FORCE","1"],["Nike","AIR","MAX","90"$
        },
        {
            "url": "atmosny.com",
           "keywords": [["Adidas","Yeezy"],["Nike","SB"],["Nike","Air","Jordan","1"],["Nike","Jordan","1"],["Nike","Jordan","11"],["Nike","Jordan","4"],["Nike","AIR","FORCE","1"],["Nike","AIR","MAX","90"$
        },
        {
            "url": "bapefrance.com",
           "keywords": [["Adidas","Yeezy"],["Nike","SB"],["Nike","Air","Jordan","1"],["Nike","Jordan","1"],["Nike","Jordan","11"],["Nike","Jordan","4"],["Nike","AIR","FORCE","1"],["Nike","AIR","MAX","90"$
        },
        {
            "url": "bdgastore.com",
           "keywords": [["Adidas","Yeezy"],["Nike","SB"],["Nike","Air","Jordan","1"],["Nike","Jordan","1"],["Nike","Jordan","11"],["Nike","Jordan","4"],["Nike","AIR","FORCE","1"],["Nike","AIR","MAX","90"$
        },
        {
            "url": "fearofgod.com",
           "keywords": [["Adidas","Yeezy"],["Nike","SB"],["Nike","Air","Jordan","1"],["Nike","Jordan","1"],["Nike","Jordan","11"],["Nike","Jordan","4"],["Nike","AIR","FORCE","1"],["Nike","AIR","MAX","90"$
        },
        {
            "url": "humanmade.jp",
           "keywords": [["Adidas","Yeezy"],["Nike","SB"],["Nike","Air","Jordan","1"],["Nike","Jordan","1"],["Nike","Jordan","11"],["Nike","Jordan","4"],["Nike","AIR","FORCE","1"],["Nike","AIR","MAX","90"$
        }

**Comment by Dam998** [comment]
why do you have a $ instead ] to close the brackets? at the end of the keywords array

However it seems to be all right

**Comment by c0deless** [comment]
yeah was an errof for the "$" but seems the monitor keeps outputing articles without using keywords.
Screenshot : https://prnt.sc/se4c84
Regards

**Comment by Dam998** [comment]
maybe you have made a mistake, 
pampamlondon.com is not in your sites list
it's impossible that the monitor notify you a product from a site not in site list
